### ISSUE TITLE
请问这个方法需要进行模型转换吗？

### ISSUE THREAD

**Issue by XiangyueLyu** [taishan1994/Llama3-Finetuning#7]
运行时没有进行模型转换，产生报错
<img width="1090" alt="截屏2024-06-21 15 42 19" src="https://github.com/taishan1994/Llama3-Finetuning/assets/169347620/9800934c-9f42-41b0-9213-b500f47f4e08">
<img width="1078" alt="截屏2024-06-21 15 42 09" src="https://github.com/taishan1994/Llama3-Finetuning/assets/169347620/407aabf3-5fd5-476d-a5bb-1797a3364f23">

**Comment by taishan1994** [comment]
不需要转换，要保证：
1. 包的版本是否一致。
2. 在命令行带参数运行。

**Comment by XiangyueLyu** [comment]
感谢您，请问python的版本是多少？

**Comment by XiangyueLyu** [comment]
非常谢谢您！目前我的环境不支持bitsandbytes0.42.0以上的版本，其他版本全部相同
(llama3_ft) [xylv@server01 script]$ pip install bitsandbytes-0.43.1-py3-none-manylinux_2_24_x86_64.whl
WARNING: Requirement 'bitsandbytes-0.43.1-py3-none-manylinux_2_24_x86_64.whl' looks like a filename, but the file does not exist
ERROR: bitsandbytes-0.43.1-py3-none-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.
(llama3_ft) [xylv@server01 script]$ python -V
Python 3.8.19 
### 目前遇到的问题是：

1. cpu optimizer不支持gcc5以下版本 实验室服务器无法变更gcc版本，于是取消cpu optimizer 遇到了以下的问题：

2. 将ds_config_zero3中的"zero_optimization"修改了"offload_optimizer": {"device": "none"},之后报错如下：

![image](https://github.com/taishan1994/Llama3-Finetuning/assets/169347620/a70e7334-47df-4c55-b802-7dfc44c8895d)
/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-06-21 22:43:27,797] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2024-06-21 22:43:27,797] [INFO] [comm.py:594:init_distributed] cdb=None
[2024-06-21 22:43:27,797] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
quantization_config： None
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:14<00:00,  3.69s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
['o_proj', 'k_proj', 'q_proj', 'v_proj']
None
trainable params: 54,525,952 || all params: 8,084,787,200 || trainable%: 0.6744265575722265
Loading data...
Formatting inputs...Skip in lazy mode
/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Traceback (most recent call last):
  File "../finetune_llama3.py", line 434, in <module>
    train()
  File "../finetune_llama3.py", line 421, in train
    trainer = Trainer(
  File "/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/transformers/trainer.py", line 527, in __init__
    raise RuntimeError(
RuntimeError: Passing `optimizers` is not allowed if Deepspeed or PyTorch FSDP is enabled. You should subclass `Trainer` and override the `create_optimizer_and_scheduler` method.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 56578) of binary: /home/xylv/anaconda3/envs/llama3_ft/bin/python
Traceback (most recent call last):
  File "/home/xylv/anaconda3/envs/llama3_ft/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xylv/anaconda3/envs/llama3_ft/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 


请问有备选的解决方案吗？非常谢谢，我的邮箱是lyuxiangyue@qq.com,如果有其他解决方案您愿意的话可以邮件给我吗？非常感谢

**Comment by taishan1994** [comment]
用zero2的配置。

**Comment by XiangyueLyu** [comment]
感谢大佬！更新啦gcc以后成功了！
